apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: opa
  name: opa
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      run: opa
  template:
    metadata:
      labels:
        run: opa
    spec:
      containers:
      - image: openpolicyagent/opa:0.9.2
        imagePullPolicy: Always
        args:
          - "run"
          - "--server"
          - "--addr=localhost:8080"
        name: opa
        resources:
          requests:
            cpu: "100m"
            memory: "30Mi"
