apiVersion: v1
kind: Pod
metadata:
  name: nginx-privileged-disallowed
  namespace: production
  labels:
    app: nginx-privileged
spec:
  containers:
    - name: nginx
      image: nginx
      securityContext:
        privileged: true